export const WORDS: string[] = [
  'above', 'actor', 'alarm', 'angel', 'apple', 'arose', 'basic', 'beach',
  'begun', 'birth', 'blade', 'blank', 'blast', 'blaze', 'bleed', 'blend',
  'blind', 'block', 'bloom', 'blown', 'board', 'bones', 'bound', 'brain',
  'brand', 'brave', 'bread', 'break', 'brick', 'brief', 'bring', 'broad',
  'brown', 'brush', 'build', 'burst', 'cabin', 'candy', 'carry', 'catch',
  'cause', 'chain', 'chair', 'charm', 'chase', 'cheap', 'check', 'chief',
  'child', 'civil', 'claim', 'class', 'clean', 'clear', 'climb', 'clock',
  'close', 'cloud', 'coach', 'coast', 'coral', 'could', 'count', 'court',
  'cover', 'crack', 'craft', 'crane', 'crash', 'crazy', 'cream', 'creek',
  'crime', 'cross', 'crowd', 'crown', 'crush', 'curve', 'dance', 'death',
  'delay', 'depth', 'doubt', 'draft', 'drain', 'drama', 'drank', 'drawn',
  'dream', 'dress', 'drift', 'drink', 'drive', 'earth', 'eight', 'elite',
  'empty', 'enemy', 'enjoy', 'enter', 'equal', 'error', 'event', 'every',
  'exact', 'extra', 'faith', 'fault', 'feast', 'fence', 'fewer', 'field',
  'fight', 'final', 'flame', 'flash', 'flesh', 'float', 'flood', 'floor',
  'flour', 'focus', 'force', 'forth', 'found', 'frame', 'frank', 'fresh',
  'front', 'frost', 'fruit', 'giant', 'given', 'glass', 'globe', 'grace',
  'grade', 'grain', 'grand', 'grant', 'grass', 'grave', 'great', 'green',
  'grind', 'gross', 'group', 'grown', 'guard', 'guess', 'guide', 'habit',
  'happy', 'harsh', 'heart', 'heavy', 'hence', 'horse', 'hotel', 'house',
  'human', 'humor', 'ideal', 'image', 'imply', 'index', 'inner', 'input',
  'issue', 'ivory', 'jewel', 'joint', 'judge', 'juice', 'knife', 'known',
  'label', 'large', 'later', 'laugh', 'layer', 'learn', 'lease', 'legal',
  'level', 'light', 'limit', 'linen', 'liver', 'local', 'logic', 'loose',
  'lover', 'lower', 'lucky', 'lunar', 'lunch', 'magic', 'major', 'manor',
  'march', 'match', 'mayor', 'meant', 'media', 'metal', 'might', 'minor',
  'minus', 'model', 'money', 'month', 'moral', 'motor', 'mount', 'mouse',
  'mouth', 'movie', 'music', 'naval', 'nerve', 'never', 'night', 'noble',
  'noise', 'north', 'noted', 'novel', 'nurse', 'ocean', 'offer', 'often',
  'order', 'organ', 'other', 'outer', 'owner', 'paint', 'panel', 'panic',
  'paper', 'party', 'pasta', 'patch', 'pause', 'peace', 'phase', 'phone',
  'photo', 'piano', 'piece', 'pilot', 'pitch', 'pixel', 'pizza', 'place',
  'plain', 'plane', 'plant', 'plate', 'plaza', 'plead', 'pluck', 'point',
  'polar', 'pound', 'power', 'press', 'price', 'pride', 'prime', 'print',
  'prior', 'prize', 'proof', 'proud', 'prove', 'psalm', 'pulse', 'punch',
  'pupil', 'queen', 'quest', 'quick', 'quiet', 'quote', 'radio', 'raise',
  'range', 'rapid', 'ratio', 'reach', 'realm', 'rebel', 'reign', 'relax',
  'rider', 'ridge', 'right', 'rigid', 'risen', 'risky', 'rival', 'river',
  'robin', 'robot', 'rocky', 'roger', 'rough', 'round', 'route', 'royal',
  'rural', 'sadly', 'saint', 'salad', 'sauce', 'scale', 'scene', 'scope',
  'score', 'sense', 'serve', 'seven', 'shade', 'shake', 'shall', 'shame',
  'shape', 'share', 'shark', 'sharp', 'sheep', 'sheer', 'shelf', 'shell',
  'shift', 'shine', 'shirt', 'shock', 'shoot', 'shore', 'short', 'shout',
  'sight', 'since', 'sixth', 'sixty', 'sized', 'skill', 'skull', 'slash',
  'slave', 'sleep', 'slice', 'slide', 'slope', 'smart', 'smell', 'smile',
  'smoke', 'snake', 'solar', 'solid', 'solve', 'sorry', 'south', 'space',
  'spare', 'spark', 'speak', 'speed', 'spend', 'spent', 'spice', 'spine',
  'split', 'spoke', 'sport', 'spray', 'squad', 'stack', 'staff', 'stage',
  'stair', 'stake', 'stand', 'stare', 'stark', 'start', 'state', 'steak',
  'steal', 'steam', 'steel', 'steep', 'steer', 'stern', 'stick', 'stiff',
  'still', 'stock', 'stone', 'stood', 'store', 'storm', 'story', 'stove',
  'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite', 'super',
  'surge', 'swear', 'sweep', 'sweet', 'swept', 'swift', 'swing', 'sword',
  'table', 'taste', 'teach', 'tempo', 'thank', 'theft', 'their', 'theme',
  'thick', 'thing', 'think', 'third', 'those', 'three', 'threw', 'throw',
  'thumb', 'tiger', 'tight', 'tired', 'title', 'today', 'token', 'topic',
  'total', 'touch', 'tough', 'tower', 'toxic', 'trace', 'track', 'trade',
  'trail', 'train', 'trait', 'trash', 'treat', 'trend', 'trial', 'tribe',
  'trick', 'troop', 'truck', 'truly', 'trump', 'trunk', 'trust', 'truth',
  'twice', 'twist', 'ultra', 'under', 'union', 'unity', 'until', 'upper',
  'upset', 'urban', 'usage', 'usual', 'valid', 'value', 'video', 'vigor',
  'viral', 'virus', 'visit', 'vital', 'vivid', 'vocal', 'voice', 'voter',
  'waste', 'watch', 'water', 'weary', 'weigh', 'weird', 'wheat', 'wheel',
  'where', 'which', 'while', 'white', 'whole', 'whose', 'width', 'woman',
  'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'wrist',
  'write', 'wrong', 'wrote', 'yacht', 'young', 'youth',
];

export function getRandomWord(): string {
  return WORDS[Math.floor(Math.random() * WORDS.length)];
}
